// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xehsdenvdwsplsbkpkyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlaHNkZW52ZHdzcGxzYmtwa3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTQwNTksImV4cCI6MjA3MTI3MDA1OX0.T8w8iXcqwuV02hEBsdDH8LBO5GL26T32WMmWb-M4JtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});